name: 'Create newsletrer campaign'
description: 'Create a new newsletter campaign at infomaniak service'
inputs:
  content:
    description: 'File path for the content'
    required: true
  subject:
    description: 'Campaign mail subject'
    required: true
  namefrom:
    description: 'Name to display in the FROM field'
    required: true
  lang:
    description: 'Campaign lang'
    default: 'en'
    required: true
  addressfrom:
    description: 'Address to display in the FROM field'
    required: true
  mailinglistid:
    description: 'List of ID for the mailing lists (1 2 3)'
    required: true

outputs:
  result:
    description: "Creation result"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${inputs.content}
    - ${inputs.subject}
    - ${inputs.namefrom}
    - ${inputs.lang}
    - ${inputs.addressfrom}
    - ${inputs.mailinglistid}

