name: 'Test newsletter campaign'
description: 'Test a draft newsletter campaign'
inputs:
  id:
    description: 'Newsletter ID'
    required: true
  dest:
    description: 'Address to send the test'
    required: true

outputs:
  result:
    description: "Test result"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${inputs.id}
    - ${inputs.dest}


