name: 'RSS to HTML'
description: 'Fetch the latest entry for a RSS feed and return the title and content'
inputs:
  rss-feed:
    description: 'RSS feed URL'
    required: true
outputs:
  article-title:
    description: "RSS feed article title"
    value: ${{ steps.random-number-generator.outputs.random-number }}
  article-content:
    description: "RSS feed article content"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.rss-feed }}

