name: 'RSS to HTML'
description: 'Fetch the latest entry for a RSS feed and return the title and content'
inputs:
  rss-feed:
    description: 'RSS feed URL'
    required: true
outputs:
  result:
    description: "RSS feed result"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.rss-feed }}

